version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
  app: 
      container_name: DSS_SERVER
      restart: always
      build: .
      ports: 
        - "3000:3000"
      volumes: 
        - . : "/usr/src/app"
        - "/usr/src/app/node_modules"
      links: 
        - mongo
